# Generated by Django 4.2.20 on 2025-05-02 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_course_teachers_course_primary_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='classroom',
            name='core_classr_name_8e5e1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='classroom',
            name='core_classr_institu_cb30c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='core_course_name_877481_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='core_course_institu_f11203_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='core_enroll_student_5b6a85_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='core_enroll_course__cb7bf3_idx',
        ),
        migrations.RemoveIndex(
            model_name='institution',
            name='core_instit_name_dda37a_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='core_studen_email_26bdb0_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='core_studen_last_na_d07597_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='core_studen_institu_9fa4bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='core_teache_email_0ea460_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='core_teache_last_na_7e664f_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='core_teache_institu_09ef6d_idx',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classroom'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('course', 'day_of_week', 'start_time')},
        ),
    ]
