# Generated by Django 4.2.20 on 2025-05-02 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_classroom_core_classr_name_8e5e1d_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
    ]
